"""add upload_ms to audio_files

Revision ID: 0b9a80712785
Revises: b9cebbfe934d
Create Date: 2026-08-23 10:36:26.147931

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0b9a80712785'
down_revision: Union[str, None] = 'b9cebbfe934d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('upload_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'upload_ms')
    # ### end Alembic commands ###