"""add diarization column to transcriptions

Revision ID: 8253b87be339
Revises: a1c4f7e93b02
Create Date: 2026-07-31 10:30:05.230390

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8253b87be339'
down_revision: Union[str, None] = 'a1c4f7e93b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('diarization', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_transcriptions_meeting_id', table_name='transcriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transcriptions_meeting_id', 'transcriptions', ['meeting_id'], unique=False)
    op.drop_column('transcriptions', 'diarization')
    # ### end Alembic commands ###